apiVersion: 1

datasources:
  - name: dryfit-postgres
    uid: dryfit-postgres
    type: postgres
    access: proxy
    isDefault: true
    url: postgres:5432
    user: grafana_reader
    secureJsonData:
      password: grafana_reader
    jsonData:
      database: dryfit
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
